# Generated by Django 5.1.4 on 2025-01-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindCallerApp', '0002_user_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
