# Generated by Django 5.1.4 on 2025-01-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindCallerApp', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
