# Generated by Django 5.1.4 on 2025-01-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindCallerApp', '0004_alter_user_options'),
        ('admin', '0003_logentry_add_action_flag_choices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
